# Generated by Django 4.1 on 2022-08-29 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time (HH:MM:SS)')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('subsystem_type', models.CharField(choices=[('AOCS', 'AOCS'), ('IMAGE', 'IMAGE PAYLOAD'), ('THERMAL', 'THERMAL'), ('POWER', 'POWER'), ('TTC', 'TTC')], default='IMAGE PAYLOAD', max_length=50)),
                ('details', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activitylog_app.satellite')),
                ('user', models.ForeignKey(default='old user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
