# Generated by Django 4.1 on 2022-09-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
    ]
